server:
  port: 9871

Spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 13
    timeout: 5000
    jedis:
      pool:
        max-wait: 100000
        max-active: 100
        max-idle: 10