server:
  port: 8991
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DataHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #http://localhost:8991/api/swagger-ui/index.html
  mvc:
    path match:
      matching-strategy: ant_path_matcher

#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  global-config:
#    db-config:
#      id-type: auto