#  ThreadPoolTaskExecutor配置
spring:
  task:
    execution:
      pool:
        # 核心线程池数
        #CPU密集设置为跟核心数一样大小，IO密集型设置为2倍CPU核心数
        core-size: 5
        # 最大线程池数
        max-size: 10
        # 任务队列的容量
        queue-capacity: 5
        # 非核心线程的存活时间
        keep-alive: 60
        # 线程池的前缀名称
      thread-name-prefix: example-task