server:
  port: 20220
  servlet:
    context-path: /table

Spring:
  mvc:
    pathmatch:
      matching-strategy:  ant-path-matcher #knife4j??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/table_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: xxxx
    password: xxxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DataHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lc.datasynch.entity
  global-config:
    db-config:
      capital-mode: true
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
